/**
 * Generate src/x402.generated.ts from the compiled contracts: the full P2FluxX402Splitter ABI and the
 * vault's creation code (what a vault address is derived from).
 *
 * `--check` compares instead of writing and exits non-zero on drift, like sync-abi.ts: the file is a
 * build output of the .sol sources in this repo, never a second editable copy.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = new URL('..', import.meta.url).pathname
const check = process.argv.includes('--check')
const artifact = (name: string) => {
  const path = join(root, 'out', `${name}.json`)
  if (!existsSync(path)) {
    console.error('no out/ - run `npm run compile` first')
    process.exit(1)
  }
  return JSON.parse(readFileSync(path, 'utf8')) as { abi: unknown; bytecode: string }
}

const next = `// GENERATED by scripts/sync-x402.ts from the compiled contracts. Do not edit: run \`npm run x402:sync\`.

/** The full P2FluxX402Splitter ABI. */
export const p2fluxX402SplitterAbi = ${JSON.stringify(artifact('P2FluxX402Splitter').abi, null, 2)} as const

/** P2FluxX402Vault creation code: \`vaultOf\` is CREATE2 over this followed by abi.encode(recipient). */
export const X402_VAULT_CREATION_CODE = '${artifact('P2FluxX402Vault').bytecode}' as const
`
const target = join(root, 'src', 'x402.generated.ts')
if (check) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== next) {
    console.error('DRIFT: src/x402.generated.ts does not match a fresh compile')
    process.exit(1)
  }
  console.log('src/x402.generated.ts matches a fresh compile')
} else {
  writeFileSync(target, next)
  console.log('wrote src/x402.generated.ts')
}
